
# General site settings
title: GeyserMC
description: >-
  Geyser is a bridge between Minecraft: Bedrock Edition and Minecraft: Java Edition
  which allows you to join Minecraft Java servers with Bedrock Edition servers to enable true cross-platform.
baseurl: ""
url: "https://geysermc.org"
twitter_username: geyser_mc
github_username: GeyserMC
discord_invite: geysermc

platforms:
  - name: spigot
    title: Spigot/Paper
    icon: img/icons/paper.png
  - name: velocity
    icon: img/icons/velocity.svg
  - name: bungee
    title: BungeeCord
    icon: img/icons/waterfall.svg
  - name: fabric
    icon: img/icons/fabric.png
  - name: standalone
    icon: img/icons/geyser.png
  - name: neoforge
    title: NeoForge
    icon: img/icons/neoforge.png
  - name: viaproxy
    title: ViaProxy
    icon: img/icons/viaproxy.png

downloads:
  geyser:
    title: Geyser
    info: "A bridge/proxy allowing you to connect to Minecraft: Java Edition servers with Minecraft: Bedrock Edition."
    setup_url: https://wiki.geysermc.org/geyser/setup/
  floodgate:
    title: Floodgate
    info: Hybrid mode plugin to allow for connections from Geyser to join online mode servers.
    setup_url: https://wiki.geysermc.org/floodgate/setup/
    external_builds:
      - title: Fabric
        link: https://modrinth.com/mod/floodgate
  # hurricane:
  #   title: Hurricane
  #   info: Fixes for Bedrock players involving server behavior modification
  #   setup: |
  #     1. Download and drop into the `plugins` folder
  #     2. Start the server

other_downloads:
  geyserconnect:
    title: GeyserConnect
    info: GeyserConnect is an easy way for Bedrock Edition clients to connect to any Java Edition servers without having to run anything.
    setup_url: https://wiki.geysermc.org/other/geyserconnect/
  # hydraulic:
  #   title: Hydraulic
  #   tags: [ "beta" ]
  #   info: "A companion mod to Geyser which allows for Bedrock players to join modded Minecraft: Java Edition servers."
  #   setup: |
  #     1. Drop the `Geyser-Fabric/Forge.jar` into the `mods` folder
  #     2. Drop the `Hydraulic.jar` into the `mods` folder
  #     3. Run the server
  geyseroptionalpack:
    title: GeyserOptionalPack
    info: Optional Bedrock resource pack to extend Geyser functionality
    setup_url: https://wiki.geysermc.org/other/geyseroptionalpack/

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"


include: [".well-known"]
